# Generated by Django 4.2.4 on 2023-11-23 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapingapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Busqueda',
            fields=[
                ('idBusqueda', models.AutoField(primary_key=True, serialize=False)),
                ('fec_bus', models.DateField()),
                ('tem_bus', models.CharField(max_length=100)),
                ('aut_bus', models.CharField(blank=True, max_length=100)),
                ('year_ini', models.CharField(blank=True, default='No establecido', max_length=10)),
                ('year_fin', models.CharField(blank=True, default='No establecido', max_length=100)),
                ('tipo_doc', models.CharField(blank=True, default='No establecido', max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='resultado',
            name='busqueda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scrapingapp.busqueda'),
        ),
    ]
